FACT_FINANCIALS_INSERT_SQL= """
INSERT INTO fact_financials (
            company_id,
            date_key,
            period_type,
            revenue,
            cost_of_revenue,            
            gross_profit,
            operating_expenses, 
            operating_income,
            net_income,
            ebit,
            ebitda,
            interest_expense,
            total_assets,
            total_liabilities,
            total_equity,
            current_assets,
            current_liabilities,
            cash_and_cash_equivalents,
            inventory,
            accounts_receivable,
            total_debt,
            operating_cash_flow,
            investing_cash_flow,
            financing_cash_flow,
            capital_expenditure,
            free_cash_flow
        )
        VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, 
                %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, 
                %s, %s, %s, %s, %s, %s)
        ON DUPLICATE KEY UPDATE
            revenue=COALESCE(VALUES(revenue), revenue),
            cost_of_revenue=COALESCE(VALUES(cost_of_revenue), cost_of_revenue),
            gross_profit=COALESCE(VALUES(gross_profit), gross_profit),
            operating_expenses=COALESCE(VALUES(operating_expenses), operating_expenses),
            operating_income=COALESCE(VALUES(operating_income), operating_income),      
            net_income=COALESCE(VALUES(net_income), net_income),    
            ebit=COALESCE(VALUES(ebit), ebit),
            ebitda=COALESCE(VALUES(ebitda), ebitda),
            interest_expense=COALESCE(VALUES(interest_expense), interest_expense),
            total_assets=COALESCE(VALUES(total_assets), total_assets),
            total_liabilities=COALESCE(VALUES(total_liabilities), total_liabilities),        
            total_equity=COALESCE(VALUES(total_equity), total_equity),
            current_assets=COALESCE(VALUES(current_assets), current_assets),
            current_liabilities=COALESCE(VALUES(current_liabilities), current_liabilities),
            cash_and_cash_equivalents=COALESCE(VALUES(cash_and_cash_equivalents), cash_and_cash_equivalents),
            inventory=COALESCE(VALUES(inventory), inventory),
            accounts_receivable=COALESCE(VALUES(accounts_receivable), accounts_receivable),
            total_debt=COALESCE(VALUES(total_debt),total_debt),
            operating_cash_flow=COALESCE(VALUES(operating_cash_flow), operating_cash_flow),
            investing_cash_flow=COALESCE(VALUES(investing_cash_flow), investing_cash_flow),
            financing_cash_flow=COALESCE(VALUES(financing_cash_flow), financing_cash_flow),
            capital_expenditure=COALESCE(VALUES(capital_expenditure), capital_expenditure),
            free_cash_flow=COALESCE(VALUES(free_cash_flow), free_cash_flow);
"""
